In [2]:
import numpy as np

lista = np.arange(0,10,1) #início / final / passo

matriz = np.array(lista)
print(matriz)
print(type(matriz))

print('\n',matriz.reshape((2,5))) #transforma em matriz: 2 linhas / 5 colunas

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>

 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [3]:
print(np.arange(10).reshape((2,5))) #se não colocar passo ele pula de 1 em 1 automaticamente

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
array = np.arange(0,110,10)
print(array)

[  0  10  20  30  40  50  60  70  80  90 100]


In [ ]:
np.zeros((2,2)) #cria uma matriz só com zeros

array([[0., 0.],
       [0., 0.]])

In [19]:
np.ones((5,2)) #cria uma matriz só com valores um

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
print(np.full((5,2),"marcus")) #cria uma matriz com o valor passado, podendo até ser strings

[['marcus' 'marcus']
 ['marcus' 'marcus']
 ['marcus' 'marcus']
 ['marcus' 'marcus']
 ['marcus' 'marcus']]


In [26]:
print(np.full((10,10),True))

[[ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


In [34]:
print(np.linspace(1,6,9)) #início / final / passo (igualmente espaçados)

print(np.linspace(2,3,5))

[1.    1.625 2.25  2.875 3.5   4.125 4.75  5.375 6.   ]
[2.   2.25 2.5  2.75 3.  ]


In [50]:
print(np.random.rand(2,2)) #os parâmetros determinam a dimensão da matriz

[[0.94293603 0.51402949]
 [0.10150769 0.86768685]]


In [51]:
print(np.random.randint(0,10,10)) #10 números inteiros aleatórios entre 0 e 10

[9 2 9 9 0 8 7 3 7 3]


### DADOS ESTATÍSTICOS DO ARRAY

In [53]:
array = np.random.randint(0,50,10)
print(array)

[45 14 34 20 21 28 19  2 24 48]


In [ ]:
array.max() #maior valor do array

48

In [55]:
array.min() # menor valor do array

2

In [56]:
array.argmax() # índice do maior valor

9

In [57]:
array.argmin() # índice do menor valor

7

In [58]:
array.mean() # média dos valores do array

25.5

In [59]:
array.std() # desvio padrão

13.207952150125317

In [60]:
array.var() # variância

174.45

In [61]:
np.median(array) # mediana

22.5

### INDEXAÇÃO DE ARRAYS

In [62]:
print(array)

[45 14 34 20 21 28 19  2 24 48]


In [63]:
array[0]

45

In [ ]:
print(array[:5]) # do começo até o quinto item

[45 14 34 20 21]


In [65]:
print(array[0:10:2]) # do primeiro ao último de 2 em 2

[45 34 21 19 24]


### COM MATRIZES

In [71]:
print(matriz)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
mat = np.random.randint(0,9,9).reshape((3,3)) #cria o array
print(mat)

impar = (mat%2 != 0) 
mat[impar] = 0
 
print('\n',mat)

In [9]:
a = np.random.randint(0,50,5)
print(a)
b = np.random.randint(0,50,5)
print(b)

[10 12 23 29  8]
[44 19 29 33 48]


In [ ]:
print(a+10) #soma com todos os elementos do array
print(np.sum(a))

[20 22 33 39 18]
82


In [11]:
print(a + b)
print(np.add(a,b))

[54 31 52 62 56]
[54 31 52 62 56]


In [12]:
print(a - b)
print(np.subtract(a,b))

[-34  -7  -6  -4 -40]
[-34  -7  -6  -4 -40]


In [ ]:
print(a * b) # multiplicação escalar
print(np.multiply(a,b))

In [13]:
a @ b # produto interno

2676

In [14]:
x=np.array([[1,2],[3,4]])
x2=np.array([[1,2],[3,4]])
y=np.array([5,6])
print(x)
print(y)
print(y.dot(x))
print(np.dot(y,x))
print()
print(np.dot(x,x2))

[[1 2]
 [3 4]]
[5 6]
[23 34]
[23 34]

[[ 7 10]
 [15 22]]


In [202]:
marcus = np.array([[2,4,6],[8,10,12]])
print(marcus,'\n')

marcus = marcus.reshape(3,2)
print(marcus,'\n')

marcus[0] = marcus[0] + 5
print(marcus,'\n')

marcus[1] = marcus[1] * 3
print(marcus,'\n')

marcus[:,1] = marcus[:,1] / 2
print(marcus)

[[ 2  4  6]
 [ 8 10 12]] 

[[ 2  4]
 [ 6  8]
 [10 12]] 

[[ 7  9]
 [ 6  8]
 [10 12]] 

[[ 7  9]
 [18 24]
 [10 12]] 

[[ 7  4]
 [18 12]
 [10  6]]


### OPERAÇÕES DE CONJUNTOS


In [203]:
np.union1d(a,b) # união (junta os valores sem repetir os iguais)

array([ 8, 10, 12, 19, 23, 29, 33, 44, 48])

In [204]:
np.intersect1d(a,b) # intersecção (valores em comum)

array([29])

In [205]:
c=np.array([1,2,2,2,6,3,3])
np.unique(c) # valores únicos do array

array([1, 2, 3, 6])

In [206]:
np.setdiff1d(a,b) # diferença entre conjuntos (valores em A que não aparecem em B)

array([ 8, 10, 12, 23])

In [ ]:
array1 = np.arange(1,11)
array2 = array1[:5].copy() #cria-se uma cópia para que ele não interfira no array1
print(array1)
print(array2)

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5]


In [208]:
array2 *= 2
print(array1)
print(array2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]


In [209]:
x= array2.flatten()
print(x)
array2[0]=3
print(array2)
print(x)

[ 2  4  6  8 10]
[ 3  4  6  8 10]
[ 2  4  6  8 10]


In [211]:
y= array2.ravel() #Retorna uma view e não uma cópia
print(y)
array2[0]=4
print(array2)
print(y)

[ 4  4  6  8 10]
[ 4  4  6  8 10]
[ 4  4  6  8 10]


In [212]:
x=np.array([[1,2],[3,4]])
print(x.T)


[[1 3]
 [2 4]]


In [ ]:
def faz_matriz(n):
    matriz = np.full((n,n),0)

    for i in range(n):
            matriz[i,i] = 1
            matriz[i,n-1-i]+=2
    return matriz

n = 6
print(faz_matriz(n))

[[1 0 0 0 0 2]
 [0 1 0 0 2 0]
 [0 0 1 2 0 0]
 [0 0 2 1 0 0]
 [0 2 0 0 1 0]
 [2 0 0 0 0 1]]


In [138]:
n = 4

m = np.floor(10*np.random.random((n,n)))
print(m,'\n')

for i in range(n):
    for j in range(n):
        
        if i == 0 and j == 0 and i < n-1 and j < n-1:
            v = m[i+1,j] + m[i,j+1]
            
        if i == 0 and j != 0 and i < n-1 and j < n-1:    
            v = m[i+1,j] + m[i,j+1] + m[i,j-1]
        
        if i != 0 and j == 0 and i < n-1 and j < n-1:
            v = m[i+1,j] + m[i,j+1] + m[i-1,j]
            
        if i != 0 and j != 0 and i < n-1 and j < n-1:
            v = m[i+1,j] + m[i,j+1] + m[i-1,j] + m[i,j-1]      
              
        print(v,end="  ")
    print()
    

[[1. 1. 0. 9.]
 [1. 8. 1. 1.]
 [9. 5. 6. 2.]
 [3. 0. 3. 1.]] 

2.0  9.0  11.0  11.0  
18.0  8.0  15.0  15.0  
9.0  23.0  11.0  11.0  
11.0  11.0  11.0  11.0  


In [17]:
import numpy as np

n = 4

m = np.random.randint(0,10, (n,n))
print(m,'\n')

for i in range(n):
    for j in range(n):
        
        v = 0
        
        if i+1 < n:
            v += m[i+1,j]
            
        if i-1 >= 0:
            v += m[i-1,j]
        
        if j+1 < n:
            v += m[i,j+1]
        
        if j-1 >= 0:
            v += m[i,j-1]
            
        print(v,end="\t")
    print()

[[2 2 0 2]
 [7 5 3 2]
 [5 1 9 9]
 [0 9 2 3]] 

9	7	7	2	
12	13	16	14	
8	28	15	14	
14	3	21	11	


In [2]:
import numpy as np

n = 4

m = np.random.randint(0,10, (n,n))
print(m,'\n')

somavizinhos = np.empty_like(m)

for i in range(n):
    for j in range(n):
        
        v = 0
        
        if i+1 < n:
            v += m[i+1,j]
            
        if i-1 >= 0:
            v += m[i-1,j]
        
        if j+1 < n:
            v += m[i,j+1]
        
        if j-1 >= 0:
            v += m[i,j-1]
            
        somavizinhos[i,j] = v
            
print(somavizinhos)

[[3 9 7 6]
 [3 0 0 3]
 [5 4 5 3]
 [6 1 9 1]] 

[[12 10 15 10]
 [ 8 16 15  9]
 [13 11 16  9]
 [ 6 19  7 12]]


In [30]:
n = 4

m = np.random.randint(0,20,(n,n))
mascara = np.empty_like(m)

print(m,"\n")

for i in range(n):
    for j in range(n):
        
        v = 1
        
        if i+1 < n and m[i+1,j] > m[i,j]:
            v = 0
            
        if i-1 < n and m[i-1,j] > m[i,j]:
            v = 0
            
        if j+1 < n and m[i,j+1] > m[i,j]:
            v = 0
            
        if j-1 < n and m[i,j-1] > m[i,j]:
            v = 0

        mascara[i,j] = v
            
print(mascara)

[[14  1 17 10]
 [ 9 13  4 11]
 [17 16 16  8]
 [12  2 17  6]] 

[[1 0 1 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 0 1 0]]


In [235]:
array = np.random.randint(0,100,(20))

print(array.reshape(4,5),'\n')

zero = array<30
um = array>=30
dois = array>=70

array[zero] = 0
array[um] = 1
array[dois] = 2

print(array.reshape(4,5))


[[45 77 98 61 60]
 [90 43 83  1 48]
 [76 24 45 29 16]
 [72 81 96 54 25]] 

[[1 2 2 1 1]
 [2 1 2 0 1]
 [2 0 1 0 0]
 [2 2 2 1 0]]


In [41]:
def faz_matriz(n):

    m = np.random.randint(0,100,(n,n))
    print(m,'\n')
    
    print(f"Máximo: {m.max()}\nMínimo: {m.min()}\nMédia: {round(m.mean(),2)}\n")

    menos_um = m<m.mean() #menores que a média
    zero = m == m.mean() #igual à média
    um = m>m.mean() #maiores que a média
    nove = m==m.max() #igual ao valor máximo
    menos_nove = m==m.min() #igual ao valor mínimo

    m[menos_um] = -1
    m[zero] = 0
    m[um] = 1
    m[nove] = 9
    m[menos_nove] = -9
     
    print(m,'\n')

valor = 4

faz_matriz(valor)


[[81 96 28 35]
 [81 48 28 70]
 [38 30 35 45]
 [89 73 91 66]] 

Máximo: 96
Mínimo: 28
Média: 58.38

[[ 1  9 -9 -1]
 [ 1 -1 -9  1]
 [-1 -1 -1 -1]
 [ 1  1  1  1]] 

