In [70]:
import numpy as np

notas = np.random.randint(0,11,(100,6))

print(f'Shape: {notas.shape}')
print(f'Dimensões: {notas.ndim}')
print(f'Tamanho: {notas.size}')

Shape: (100, 6)
Dimensões: 2
Tamanho: 600


In [71]:
douzi = notas.reshape(50,12)
antigo = douzi.reshape(100,6)

print(douzi)
print()
print(antigo)

[[ 3  5  6  6  5  9  4  0  8  2  8  0]
 [ 7  2  8  6  8  6  1  9  8  2  4  1]
 [ 6  8  0  8  1  2  4  3  0  4  3  5]
 [ 7  8  9  0  0  4  2  6  4 10  7  3]
 [10  9  6  4  1  0  2  4  9  1  1  8]
 [ 6  7  1  7  6  3  9  0  9  7  2  8]
 [ 3  4  7  1  1  4  9  0  5  4  9  4]
 [ 5  7  3  8  9  7  6  8  0  3  0  4]
 [ 0  9  0  5  3  1 10  7  5  3  7  7]
 [ 5  7  7  2  8  3  0  2  1  7  8  1]
 [ 8  4 10 10  1  4 10 10  5  3  2  0]
 [10  4  5  5  4  8  8  0  5  9  9  4]
 [ 8 10  8  6  5  9  1  4  5  9  5  2]
 [ 9  9  8  7  6  0  6  7  6  0  8  9]
 [ 3  8  3  8  9  1  5  8 10 10  0 10]
 [10  2  3  7  5  7  8  3  0  0  6  1]
 [ 9  1  9  0  0  5  4  3  7  1 10  5]
 [ 8  2  4  8  9  8  8  8  7  8  3  4]
 [ 0  9  2  2  1  0 10  7  6  3  3  0]
 [ 3  9  5  6  9  1  1  7  4  1  0  1]
 [ 0  4  7  7  4  8  6  2  4  6 10  4]
 [ 9  5  0  6  3 10  5  5  6  1  4  1]
 [ 1  4  0  6  3  4  7  7  7  9 10  2]
 [ 5  1  6  9  4  4  0  9  8  5  1  1]
 [ 2  1  9  5  6  9  9 10  2  2  9  5]
 [10  4  4  8  3  2  8  7

In [72]:
print(notas[10,3])
print()
print(notas[20:30,2:4])

7

[[10 10]
 [ 5  3]
 [ 5  5]
 [ 5  9]
 [ 8  6]
 [ 5  9]
 [ 8  7]
 [ 6  0]
 [ 3  8]
 [10 10]]


In [73]:
print(notas[1])

notas[notas < 5] = 5

print(notas[1])

[4 0 8 2 8 0]
[5 5 8 5 8 5]


In [74]:
print(notas[1])

notas = notas + 0.5

print(notas[1])

[5 5 8 5 8 5]
[5.5 5.5 8.5 5.5 8.5 5.5]


In [75]:
media = round(notas.mean())

print(media)

print(notas[1])

diff = notas - media

print(diff[1])

7
[5.5 5.5 8.5 5.5 8.5 5.5]
[-1.5 -1.5  1.5 -1.5  1.5 -1.5]


In [77]:
print(notas.mean(axis=0)) #percorre colunas
print(notas.mean(axis=1)) #percorre linhas 

[6.9  7.07 7.04 6.85 6.69 6.56]
[6.5        6.5        7.16666667 6.66666667 6.66666667 5.5
 7.         6.83333333 7.16666667 6.66666667 6.5        7.66666667
 5.83333333 6.83333333 7.33333333 6.16666667 6.16666667 7.33333333
 6.66666667 6.33333333 7.66666667 7.16666667 6.83333333 7.33333333
 8.16666667 6.16666667 7.83333333 7.33333333 7.16666667 8.5
 7.         6.16666667 6.83333333 6.66666667 7.66666667 7.33333333
 6.16666667 6.83333333 7.         5.83333333 6.66666667 6.66666667
 7.16666667 5.66666667 5.66666667 8.         6.33333333 6.66666667
 7.         7.66666667 6.83333333 7.         6.33333333 8.
 7.33333333 7.16666667 6.33333333 6.         6.83333333 7.83333333
 7.5        6.66666667 6.5        7.         6.33333333 6.5
 7.16666667 8.33333333 6.         7.16666667 7.5        5.66666667
 6.66666667 6.5        7.33333333 5.66666667 7.66666667 7.66666667
 7.         6.83333333 5.83333333 6.5        7.66666667 5.83333333
 7.16666667 7.16666667 5.5        6.33333333 7.5        7.1

In [ ]:
print(notas.max(axis=1))
print(notas.std()) #desvio padrão


[ 9.5  8.5  8.5  9.5  8.5  5.5  9.5 10.5 10.5  9.5  7.5  9.5  7.5  9.5
  9.5  8.5  9.5 10.5  8.5  8.5 10.5 10.5 10.5  9.5 10.5  9.5  9.5  9.5
  9.5 10.5 10.5  8.5  9.5 10.5  9.5  8.5  9.5 10.5  9.5  7.5  8.5 10.5
 10.5  6.5  6.5 10.5  9.5  9.5  9.5 10.5 10.5  8.5  8.5 10.5 10.5 10.5
  8.5  8.5 10.5 10.5 10.5  8.5  7.5 10.5  8.5 10.5 10.5 10.5  6.5 10.5
 10.5  6.5 10.5  9.5 10.5  6.5  9.5 10.5  9.5 10.5  7.5  9.5 10.5  6.5
 10.5 10.5  5.5  8.5 10.5 10.5 10.5  9.5  8.5  9.5 10.5  9.5 10.5  7.5
  8.5  8.5]
1.71794369976305


In [ ]:
maior = notas.max()

indices = np.argwhere(notas == maior)

print(indices)

[[ 7  3]
 [ 8  0]
 [17  0]
 [20  2]
 [20  3]
 [21  0]
 [21  1]
 [22  0]
 [24  1]
 [29  2]
 [29  3]
 [29  5]
 [30  0]
 [33  4]
 [37  0]
 [41  4]
 [42  5]
 [45  4]
 [49  1]
 [50  0]
 [53  5]
 [54  2]
 [55  3]
 [58  3]
 [59  3]
 [60  3]
 [60  5]
 [63  3]
 [65  4]
 [66  1]
 [66  4]
 [67  1]
 [69  2]
 [70  5]
 [72  2]
 [74  3]
 [77  2]
 [79  5]
 [82  1]
 [84  1]
 [84  4]
 [85  1]
 [88  0]
 [89  1]
 [90  1]
 [94  5]
 [96  0]]


In [94]:
print(np.where(notas >= 7,True,False))

[[False False False False False  True]
 [False False  True False  True False]
 [ True False  True False  True False]
 [False  True  True False False False]
 [False  True False  True False False]
 [False False False False False False]
 [ True  True  True False False False]
 [False False False  True  True False]
 [ True  True False False False False]
 [False False  True False False  True]
 [False  True False  True False False]
 [ True False  True  True False  True]
 [False False  True False False False]
 [ True False False False  True False]
 [False  True False  True  True  True]
 [False  True False False False False]
 [False  True False False False False]
 [ True  True False False  True  True]
 [False  True  True False  True False]
 [False False False  True  True False]
 [ True False  True  True False False]
 [ True  True False False False False]
 [ True False False False False  True]
 [ True False False  True  True False]
 [ True  True  True False False  True]
 [False False False  True

In [ ]:
sete_maior = notas[notas >= 7]
print(sete_maior)

<class 'numpy.ndarray'>


In [107]:
medias = notas.mean(axis=1)

medias = medias[medias>=7]

print(medias.size)

48


In [113]:
grupo_a = np.array([0,1,2,3,4])
grupo_b = np.array([3,4,5,6,7])

#inteseção
print(np.intersect1d(grupo_a,grupo_b))

#união
print(np.union1d(grupo_a,grupo_b))

#diferença
diferença = grupo_a - grupo_b
print(diferença)


[3 4]
[0 1 2 3 4 5 6 7]
[-3 -3 -3 -3 -3]


In [114]:
x_max = notas.max()
x_min = notas.min()

normalizadas = (notas - x_min) / (x_max - x_min)

print(normalizadas)

[[0.  0.  0.2 0.2 0.  0.8]
 [0.  0.  0.6 0.  0.6 0. ]
 [0.4 0.  0.6 0.2 0.6 0.2]
 [0.  0.8 0.6 0.  0.  0. ]
 [0.2 0.6 0.  0.6 0.  0. ]
 [0.  0.  0.  0.  0.  0. ]
 [0.4 0.6 0.8 0.  0.  0. ]
 [0.  0.2 0.  1.  0.4 0. ]
 [1.  0.8 0.2 0.  0.  0. ]
 [0.  0.  0.8 0.  0.  0.6]
 [0.2 0.4 0.  0.4 0.2 0. ]
 [0.8 0.  0.8 0.4 0.  0.6]
 [0.  0.  0.4 0.  0.  0. ]
 [0.8 0.  0.  0.  0.8 0. ]
 [0.  0.4 0.  0.6 0.8 0.4]
 [0.2 0.6 0.  0.  0.  0. ]
 [0.  0.8 0.  0.  0.  0. ]
 [1.  0.4 0.  0.  0.4 0.4]
 [0.  0.4 0.4 0.  0.6 0. ]
 [0.  0.  0.  0.4 0.6 0. ]
 [0.6 0.  1.  1.  0.  0. ]
 [1.  1.  0.  0.  0.  0. ]
 [1.  0.  0.  0.  0.  0.6]
 [0.6 0.  0.  0.8 0.8 0. ]
 [0.6 1.  0.6 0.2 0.  0.8]
 [0.  0.  0.  0.8 0.  0. ]
 [0.8 0.8 0.6 0.4 0.2 0. ]
 [0.2 0.4 0.2 0.  0.6 0.8]
 [0.  0.6 0.  0.6 0.8 0. ]
 [0.  0.6 1.  1.  0.  1. ]
 [1.  0.  0.  0.4 0.  0.4]
 [0.6 0.  0.  0.  0.2 0. ]
 [0.8 0.  0.8 0.  0.  0. ]
 [0.  0.  0.4 0.  1.  0. ]
 [0.6 0.  0.  0.6 0.8 0.6]
 [0.6 0.6 0.4 0.6 0.  0. ]
 [0.  0.8 0.  0.  0.  0. ]
 

In [119]:
import pandas as pd

df = pd.read_csv('diamonds.csv',sep=';')

df.head()

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.70,Ideal,E,SI1,62.5,57.0,2757,5.70,5.72,3.57
1,0.86,Fair,E,SI2,55.1,69.0,2757,6.45,6.33,3.52
2,0.70,Ideal,G,VS2,61.6,56.0,2757,5.70,5.67,3.50
3,0.71,Very Good,E,VS2,62.4,57.0,2759,5.68,5.73,3.56
4,0.78,Very Good,G,SI2,63.8,56.0,2759,5.81,5.85,3.72


In [122]:
print(f'total de diamantes: {df.size}')

total de diamantes: 11140


In [126]:
print(f'tipos de corte: {df['cut'].unique()}')

tipos de corte: ['Ideal' 'Fair' 'Very Good' 'Good' 'Premium']


In [162]:
naosei = df.groupby('cut')['cut'].count()
print(f'corte mais frequente: {naosei.idxmax()}')


corte mais frequente: Ideal


In [163]:
print(df.groupby('cut')['price'].mean())

cut
Fair         2929.727273
Good         2918.625000
Ideal        2923.245902
Premium      2901.816406
Very Good    2930.296992
Name: price, dtype: float64


In [170]:
filtro = df[(df['carat'] > 0.75) & (df['cut'] == 'Ideal')]
print(filtro)

      carat    cut color clarity  depth  table  price     x     y     z
14     0.80  Ideal     I     VS1   62.9   56.0   2760  5.94  5.87  3.72
18     0.81  Ideal     F     SI2   58.8   57.0   2761  6.14  6.11  3.60
20     0.80  Ideal     F     SI2   61.4   57.0   2761  5.96  6.00  3.67
29     0.80  Ideal     F     SI2   59.9   59.0   2762  6.01  6.07  3.62
41     0.79  Ideal     F     SI2   61.9   55.0   2771  5.97  5.92  3.68
...     ...    ...   ...     ...    ...    ...    ...   ...   ...   ...
1074   0.79  Ideal     E     SI1   62.9   55.0   3075  5.93  5.86  3.71
1083   0.76  Ideal     E     VS2   61.3   56.0   3079  5.79  5.83  3.56
1087   1.00  Ideal     H      I1   61.3   57.0   3080  6.41  6.44  3.94
1096   0.79  Ideal     F     SI1   62.0   55.0   3081  5.93  5.95  3.68
1106   0.80  Ideal     F     SI1   61.0   56.0   3082  6.05  5.98  3.67

[141 rows x 10 columns]


In [172]:
df['volume'] = df['x'] * df['y'] * df['z']
df

,carat,cut,color,clarity,depth,table,price,x,y,z,volume
0,0.70,Ideal,E,SI1,62.5,57.0,2757,5.70,5.72,3.57,116.396280
1,0.86,Fair,E,SI2,55.1,69.0,2757,6.45,6.33,3.52,143.716320
2,0.70,Ideal,G,VS2,61.6,56.0,2757,5.70,5.67,3.50,113.116500
3,0.71,Very Good,E,VS2,62.4,57.0,2759,5.68,5.73,3.56,115.865184
4,0.78,Very Good,G,SI2,63.8,56.0,2759,5.81,5.85,3.72,126.437220
...,...,...,...,...,...,...,...,...,...,...,...
1109,0.92,Premium,F,SI2,62.1,60.0,3083,6.21,6.26,3.87,150.444702
1110,0.72,Very Good,F,VS1,63.2,57.0,3083,5.69,5.73,3.61,117.699357
1111,1.01,Premium,H,SI2,59.4,62.0,3083,6.47,6.43,3.83,159.336043
1112,0.71,Very Good,D,VS2,61.8,55.0,3084,5.72,5.74,3.54,116.228112


In [173]:
import pandas as pd

df = pd.read_csv('clientes.csv')